kotlin.code.style=official
org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m
org.gradle.parallel=true

gradleVersion=9.7.0
kotlinVersion=2.3.20
javaVersion=25
ktorVersion=3.1.1
ktorOpenApiVersion=5.2.0
schemaKeneratorVersion=2.2.0
logbackVersion=1.5.16
junitVersion=5.11.4
flywayVersion=11.1.0
postgresqlVersion=42.7.4
testcontainersVersion=1.20.4
